version: '3.7'

services:
    postgis:
        image: kartoza/postgis:13.0
        restart: always
        container_name: postgis
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - '5432:5432'

    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        links:
            - postgis
    # pg admin is not up in aws

    web:
        build:
            context: .
        restart: always
        volumes:
            - static-data:/vol/web
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - SECRET_KEY=${SECRET_KEY}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        depends_on:
            - postgis
    proxy:
        build:
            context: ./proxy
        restart: always
        depends_on:
            - web
        ports:
            - 80:8000
        volumes:
            - static-data:/vol/static

volumes:
    postgres_data:
    static-data: